apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
  #namespace: dapr-workshop
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: externalinfrastructure
  - name: port
    value: 4025
  - name: user
    secretKeyRef:
      name: smtp
      key: user
  - name: password
    secretKeyRef:
      name: smtp
      key: password
  - name: skipTLSVerify
    value: true
auth:
  secretStore: dapr-workshop-secrets
scopes:
  - finecollectionservice