apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  #namespace: dapr-workshop
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: externalinfrastructure:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - trafficcontrolservice